### ISSUE TITLE
linecache.git is trying to install while executing command "bundle install --without development oracle_enabled"

### ISSUE THREAD

**Issue by kirantpatil** [evgeniy-khatko/tarantula#11]
Hi,

I updated the master branch. I am getting below error while installing in production mode
## Observation:
1. I am trying to install in without development and oracle_enabled mode but it still 
   trying to install gems from development group
2. As in earlier issue I pointed gems permission problem comes when the 
   below format is used
   `git clone 'git@github.com:mark-moseley/linecache.git'
## Error:

fossqc@patchbee:~/test/tarantula$ bundle install --without development oracle_enabled
Fetching gem metadata from http://rubygems.org/........
Fetching gem metadata from http://rubygems.org/..
Fetching git@github.com:mark-moseley/linecache.git
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Git error: command `git clone 'git@github.com:mark-moseley/linecache.git'
"/home/fossqc/.rvm/gems/ruby-1.9.3-p429/cache/bundler/git/linecache-7eade00a5c1dfe3ce114b88395d5e288c138e96c"
--bare --no-hardlinks` in directory /home/fossqc/test/tarantula has failed.

Thanks,
Kiran.

**Comment by evgeniy-khatko** [comment]
This is probably because gems with :git flag always gets updated, no mater of the group..
You could try 2 things:
1. change :git path to "https://github.com/mark-moseley/linecache.git"
2. comment line "gem 'linecache19', :git => 'git@github.com:mark-moseley/linecache.git'"

**Comment by evgeniy-khatko** [comment]
You could also try to remove Gemfile.lock and "bundle install"

**Comment by kirantpatil** [comment]
resolved. closing this.
