### ISSUE TITLE
Не производится экспорт кейсов тестового сценария OTT Hub - OpCo Integration Testing из баг-трекинговой системы Tarantula.

### ISSUE THREAD

**Issue by lampo4ka** [evgeniy-khatko/tarantula#15]
Действие: экспорт кейсов тестового сценария OTT Hub - OpCo Integration Testing из баг-трекинговой системы Tarantula и сохранение их в файл текстового формата на компьютер.

Ожидаемый результат: сохранение экспортируемого тест-кейса на компьютер в текстовый файл.

Реальный результат: при экспорте тест-кейсов разного содержания все время происходит сохранение одного и того же кейса, который был сохранен до этого.

**Comment by evgeniy-khatko** [comment]
fixed
