### ISSUE TITLE
git clone and accessing gem issues

### ISSUE THREAD

**Issue by kirantpatil** [evgeniy-khatko/tarantula#7]
Please let me know, if I am right here.

I followed your install guide and could not clone your repo, so I cloned as follows,
git clone https://github.com/evgeniy-khatko/tarantula
## While bundle install, I had below issue

fossqc@patchbee:~/tarantula$ bundle install --without development oracle_enabled
Fetching gem metadata from http://rubygems.org/........
Fetching gem metadata from http://rubygems.org/..
Fetching git@github.com:sandrods/odf-report.git
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Git error: command `git clone 'git@github.com:sandrods/odf-report.git'
"/home/fossqc/.rvm/gems/ruby-2.0.0-p195/cache/bundler/git/odf-report-c45bc9cc9dbd8225d0545230901f27b4b66b9dc2" --bare --no-hardlinks` in directory
/home/fossqc/tarantula has failed.
## The solution

I replaced the git clone 'git@github.com:sandrods/odf-report.git line by
gem 'odf-report', :git => 'https://github.com/sandrods/odf-report'

Thanks.

**Comment by evgeniy-khatko** [comment]
Thanks, added this issue to the INSTALL instructions
